### ISSUE TITLE
pump current monitor and board-temp interface

### ISSUE THREAD

**Issue by iot-root** [iot-root/garden-of-eden#37]
**Requirements**

TBD

The pump current monitor interface:
- [ ] shall program a over temp limit of X
- [ ] when pin is triggered the pump shall turn off?

**Notes**
- CHANNEL_TEMP_INTER:  25
- THRESH_TEMP_INTER: 70

**Comment by petercorrea** [comment]
Closing in favor of https://github.com/iot-root/garden-of-eden/issues/33
