### ISSUE TITLE
dimmer function in the led.py turns off lights

### ISSUE THREAD

**Issue by doubleplusthink** [iot-root/garden-of-eden#39]
For me, when I used the dimmer() function in the LED class, it turned off my gardyn lights.  

Can someone repro this to see if it's a problem for them as well?

**Comment by iot-root** [comment]
Not sure we need anything other than on, off, get and adjust. I looked at that function and I dont see the point of it or "lighter"

**Comment by ammaratef45** [comment]
I think `min` here was supposed to be `max` - likely a bug
https://github.com/iot-root/gardyn-of-eden/blob/93ac7cae6adc6d5b98c1c75f967876254ae9883f/sensors/led.py#L74

**Comment by iot-root** [comment]
not using a dim function
